import numpy as np

# Installation:
# Download 33M-grouplens.zip from Grouplens - the alternative name is ml-latest.
# Extract it into RawData.
# Some aggregations are in the repo. Others are not. They should be generated by running generate_aggregations() FROM THIS FILE.

aggregation_path = "../" * int(__name__ == "__main__") + "RawData/33M-grouplens/" # Jank, very contextual
# Files:
# - genome-scores.csv ~ 520M
# - genome-tags.csv ~ 18K
# - links.csv ~ 1.9M
# - movies.csv ~ 4.2M
# - ratings.csv ~ 930M - relevant for most data processing (each user has around 100 ratings)
# - tags.csv ~ 85M
# Aggregations (not present in all datasets):
# - genome-movies ~ 92K
# - genome-vectors.csv ~ 307M
# - genome-vectors-split.csv ~ 229M
# - genre-movies.csv ~ 560K
# - genre-vectors-split.csv ~ 3.3M
total_rating_count = 32000000
default_offset = 2000000 # 5000000
total_user_count = 330975
gene_count = 1128


def get_rating_samples(count: int | None = None, offset: int = 0, file: str = aggregation_path + "ratings.csv"):
	"""Gets samples from a movie rating dataset. If count is left unset, it reads all ratings.
	Always set file if importing this function (since the relative path breaks if this function is called from elsewhere)."""
	return np.loadtxt(file,
	                  delimiter=',', max_rows=count, skiprows=1 + offset) # dtype="int,int,float,int" - saved memory, prevented it from being a 2d array


# def get_movie_genres(file: str = aggregation_path + "movies.csv"):
# 	movies_data = np.loadtxt(file,
# 	                         delimiter=',', quotechar='\"', comments=None, dtype=str, skiprows=1)
# 	# def format_genres(data): return np.array([int(data[0]), data[2].split('|')])
# 	# format_genres = np.vectorize(format_genres)
# 	# return format_genres(movies_data)
# 	# return np.array([np.array([int(data[0]), data[2].split('|')], dtype="object") for data in movies_data])
# 	return {int(data[0]): data[2].split('|') for data in movies_data}


def get_movie_genres(file: str = aggregation_path + "genre-vectors-split.csv"):
	movie_genre_data = np.loadtxt(file,
	                              delimiter=',', skiprows=1)
	movie_genre_ids = np.loadtxt('/'.join(file.split('/')[:-1]) + "/genre-movies.csv",
	                             delimiter=',', skiprows=1)
	return {movie_id: movie_genre_data[i] for i, movie_id in enumerate(movie_genre_ids)}


def get_movie_genome_scores_raw(file: str = aggregation_path + "genome-scores.csv"):
 	movie_genome_data = np.loadtxt(file,
 	                               delimiter=',', skiprows=1)
 	movie_count = len(movie_genome_data) // gene_count
 	return {movie_genome_data[i * gene_count][0]: movie_genome_data[i * gene_count:(i + 1) * gene_count, 2] for i in range(movie_count)}


# def get_movie_genome_scores(file: str = aggregation_path + "genome-vectors.csv"):
# 	# From aggregated vectors
# 	movie_genome_data = np.loadtxt(file,
# 	                               delimiter=',', dtype=str, skiprows=1)
# 	return {int(data[0]): np.array(data[1].split('|')).astype(np.float64) for i, data in enumerate(movie_genome_data)}


def get_movie_genome_scores(file: str = aggregation_path + "genome-vectors-split.csv"):
	# From split aggregated vectors
	movies_genome_data = np.loadtxt(file,
	                               delimiter=',')
	movie_ids = np.loadtxt('/'.join(file.split('/')[:-1]) + "/genome-movies.csv",
	                              delimiter=',', skiprows=1)
	return {movie_id: movie_genome_data for movie_id, movie_genome_data in zip(movie_ids, movies_genome_data)}


def get_scores(file: str):
	return np.loadtxt(file, skiprows=1)


def get_matrix(file: str):
	return np.loadtxt(file, delimiter=',')


def save_ratings(out_name, ratings):
	np.savetxt(out_name, ratings,
	           fmt='%d,%d,%.1f,%d', comments="", header="userId,movieId,rating,timestamp")


def save_scores(out_name, scores):
	np.savetxt(out_name, scores,
	           fmt='%.10f', comments="", header="score")


def save_matrix(out_name, matrix):
	width = len(matrix[0])
	np.savetxt(out_name, matrix,
	           fmt='%.10f'+',%.10f'*(width-1), comments="")


def select_ratings(rating_count: int, ratings):
	"""Selects a random sample of ratings."""
	ratings_filter = np.random.choice(np.arange(len(ratings)), size=min(len(ratings), rating_count), replace=False)
	return ratings[ratings_filter]


def select_ratings_user(user_count: int, ratings):
	"""Selects ratings grouped by random users. Each movie has an average of 100 ratings."""
	last_user = ratings[-1][0]
	users = np.random.choice(np.arange(1, last_user), size=min(last_user, user_count), replace=False) # omits last user (as data may be cut off)
	users_filter = np.isin(ratings[:, 0], users)
	ratings_filtered = ratings[users_filter] # [ratings[i] for i in range(len(ratings)) if ratings[i][0] in users]
	return ratings_filtered


def select_ratings_movie(movie_count: int, ratings):
	"""Selects ratings grouped by random movies. Each movie has an average of 400 ratings, though with a smaller rating set that value is smaller.
	Note that this function does not return all ratings for a movie, but all ratings found within the first sample_count samples.
	Note the bias towards more popular movies."""
	all_movies = np.unique(ratings[:, 1])
	# all_movies = np.unique([rating[1] for rating in ratings])
	movies = np.random.choice(all_movies, size=min(len(all_movies), movie_count), replace=False)
	movies_filter = np.isin(ratings[:, 1], movies)
	ratings_filtered = ratings[movies_filter] # [ratings[i] for i in range(len(ratings)) if ratings[i][1] in movies]
	return ratings_filtered


def main() -> None:
	# Recommended to use twice as many samples as required:
	# Each user has an average of 100 ratings.
	# Each movie has an average of 400 ratings.
	save = True
	# test_set = True
	samples_test = get_rating_samples(default_offset, offset=default_offset)
	samples = get_rating_samples(default_offset)

	# sample = select_ratings(pow(10, 6), samples)
	# sample_user = select_ratings_user(pow(10, 4), samples)
	# sample_movie = select_ratings_movie(pow(10, 4), samples)
	if save:
		save_ratings(f"sample-all-test.csv", samples_test)
		# save_ratings(f"sample{int(test_set) * "-test"}.csv", sample)
		# save_ratings(f"sample-user{int(test_set) * "-test"}.csv", sample_user)
		# save_ratings(f"sample-movie{int(test_set) * "-test"}.csv", sample_movie)
		save_ratings(f"sample-all.csv", samples)


def generate_aggregations() -> None:
	print("Getting genome scores...")
	genome_scores = get_movie_genome_scores_raw()

	print("Saving aggregate data...")
	np.savetxt(aggregation_path + "genome-vectors.csv", [[str(int(k)) + ',' + '|'.join(v.astype(str))] for k, v in genome_scores.items()],
	           fmt='%s', comments="", header="movieId,relevanceVector")
	save_matrix(aggregation_path + "genome-vectors-split.csv", list(genome_scores.values()))


if __name__ == "__main__":
	# generate_aggregations()
	main()
